name: Code Review - Post pull request
on:
  workflow_dispatch:
    inputs:
      pull_request_id:
        required: true
        description: Pull Request ID
        type: string

jobs:
  m0:
    name: M0 - Estándar de branch y commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M0
        id: m0
        uses: j1myx/githubactionbase@main
        with:
          pull_request_id: ${{ github.event.inputs.pull_request_id }}
          metric: 'm0'