name: Code Review - Pull request
on:
  pull_request:
    branches:
      - '**'

jobs:
  m0:
    name: M0 - Estándar de branch y commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M0
        id: m0
        uses: j1myx/githubactionbase@main
        with:
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm0'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  m1:
    name: M1 - Manejo de commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M1
        id: m1
        uses: j1myx/githubactionbase@main
        with:
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm1'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  m2:
    name: M2 - Creación de PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M2
        id: m2
        uses: j1myx/githubactionbase@main
        with:
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm2'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  m3:
    name: M3 - Revisión de Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M3
        id: m3
        uses: j1myx/githubactionbase@main
        with:
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm3'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  m4:
    name: M4 - Observación de Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M4
        id: m4
        uses: j1myx/githubactionbase@main
        with:
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm4'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  m5:
    name: M5 - PR abierto por más de 7 días
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M5
        id: m5
        uses: j1myx/githubactionbase@main
        with:
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm5'
          github_token: ${{ secrets.GITHUB_TOKEN }}