name: Code Review - Pre pull request
on:
  workflow_dispatch:
    inputs:
      destination_branch:
        required: true
        description: Destination branch
        type: string
        default: develop

jobs:
  m0:
    name: M0 - Estándar de branch y commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M0
        id: m0
        uses: j1myx/githubactionbase@main
        with:
          origin_branch: ${{ github.event.ref }}
          destination_branch: ${{ github.event.inputs.destination_branch }}
          metric: 'm0'