name: Code Review - Pull request
on:
  pull_request:
    branches:
      - '**'

jobs:
  m0:
    name: M0 - Estándar de branch y commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: M0
        id: m0
        uses: j1myx/githubactionbase@main
        with:
          origin_branch: ${{ github.event.pull_request.head.ref }}
          destination_branch: ${{ github.event.pull_request.base.ref }}
          metric: 'm0'